# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#

version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: create awsconfiguration.json
          command: |
            echo ${awsconfiguration} | base64 --decode >> awsconfiguration.json
      - run:
          name: runInstrumentationTest
          command: |
            bash circleciscriptios.sh
workflows:
  version: 2

  build_and_test:
    jobs:
      - build