# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  run_ui_test:
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Run Sample UI Test
          command: |
            git clone https://github.com/awslabs/aws-sdk-ios-samples.git
            cfolder=$(pwd)
            cd aws-sdk-ios-samples
            cd S3TransferUtility-Sample/Swift/
            echo ${awsconfiguration} | base64 --decode > S3BackgroundTransferSampleSwift/awsconfiguration.json
            cat S3BackgroundTransferSampleSwift/awsconfiguration.json
            pod install
            xcodebuild -workspace S3TransferUtilitySampleSwift.xcworkspace -scheme "S3TransferUtilitySampleSwiftUITests" -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.2' test
            cd $cfolder

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_ui_test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+.[0-9]+.[0-9]+$/